import type {
  GateDefinition,
  GatePenalty,
  GateRewardTable,
  Item,
  MonsterDefinition,
  Quest,
  RandomQuestTemplate,
  SkillDefinition,
} from './types'
import { todayISO } from './game'

export const DEFAULT_DAILIES: Quest[] = [
  // ── 매일 (cooldownDays 0) ─────────────────────────────────────────
  {
    id: 'daily-news',
    title: '경제신문 30분',
    description: '한경/매경 또는 Bloomberg, Reuters 등에서 거시·산업·기업 기사 30분 정독.',
    category: 'study',
    difficulty: 'hard',
    statRewards: { INT: 2 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-kbi',
    title: 'KBI 금융 AI 리터러시 1시간',
    description: '강의 수강 또는 문제풀이 1시간.',
    category: 'study',
    difficulty: 'hard',
    statRewards: { INT: 2 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-market-close',
    title: '시장 마감 점검',
    description: '코스피·S&P500 종가 + 주요 이슈 1줄 요약 기록 (10분).',
    category: 'study',
    difficulty: 'normal',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-gym',
    title: '헬스장 출석',
    description: '분할 루틴대로 웨이트 운동 완료.',
    category: 'health',
    difficulty: 'normal',
    statRewards: { STR: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-cardio',
    title: '유산소 30분',
    description: '성북천 러닝 또는 헬스장 러닝머신·사이클 30분.',
    category: 'health',
    difficulty: 'normal',
    statRewards: { VIT: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-protein',
    title: '단백질 100g+ 섭취',
    description: '커팅 중 근손실 방지. 닭가슴살·계란·프로틴·두부 등.',
    category: 'health',
    difficulty: 'normal',
    statRewards: { VIT: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-water',
    title: '물 2L+ 마시기',
    description: '커팅 + 신진대사. 종일 분산해서.',
    category: 'health',
    difficulty: 'easy',
    statRewards: { VIT: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-sleep',
    title: '23시 전 취침 / 7시 전 기상',
    description: '수면·기상 리듬 회복.',
    category: 'mind',
    difficulty: 'easy',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-no-phone-morning',
    title: '기상 후 1시간 폰 안 보기',
    description: '아침 도파민 보호. 기상 직후 60분 동안 폰 잠금.',
    category: 'mind',
    difficulty: 'easy',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-shortform-limit',
    title: '숏폼 시청 30분 이내',
    description: '인스타 릴스/유튜브 쇼츠/틱톡 누적 30분 이내.',
    category: 'mind',
    difficulty: 'easy',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-review',
    title: '하루 회고 3줄',
    description: '잘한 것 / 못한 것 / 내일 할 것 각 1줄.',
    category: 'mind',
    difficulty: 'easy',
    statRewards: { SEN: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-meditate',
    title: '명상 / 호흡 10분',
    description: '집중력·스트레스 관리.',
    category: 'mind',
    difficulty: 'easy',
    statRewards: { SEN: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },
  {
    id: 'daily-bed',
    title: '이불 정리',
    description: '기상 직후 1분. 하루 첫 성취.',
    category: 'habit',
    difficulty: 'easy',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    createdAt: todayISO(),
  },

  // ── cooldownDays 1 (격일) ─────────────────────────────────────────
  {
    id: 'daily-read',
    title: '독서 30분',
    description: '전공·금융 외 일반 도서 (자기계발/소설/인문 등).',
    category: 'study',
    difficulty: 'normal',
    statRewards: { INT: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 1,
    createdAt: todayISO(),
  },
  {
    id: 'daily-stretch',
    title: '샤워 후 스트레칭 5분',
    description: '가동성·자세 교정.',
    category: 'health',
    difficulty: 'easy',
    statRewards: { AGI: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 1,
    createdAt: todayISO(),
  },

  // ── cooldownDays 2 (3일 주기) ─────────────────────────────────────
  {
    id: 'daily-cleaning',
    title: '방 청소 / 설거지',
    description: '자취방 위생 유지.',
    category: 'habit',
    difficulty: 'normal',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 2,
    createdAt: todayISO(),
  },
  {
    id: 'daily-weigh',
    title: '공복 체중 기록',
    description: '커팅 트래킹. 아침 기상 직후 측정.',
    category: 'health',
    difficulty: 'easy',
    statRewards: { SEN: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 2,
    createdAt: todayISO(),
  },
  {
    id: 'daily-finance-media',
    title: '금융 유튜브/팟캐스트 1편',
    description: '삼프로TV, 김작가TV, 슈카월드 등 1편 시청.',
    category: 'study',
    difficulty: 'normal',
    statRewards: { INT: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 2,
    createdAt: todayISO(),
  },

  // ── cooldownDays 3 (4일 주기) ─────────────────────────────────────
  {
    id: 'daily-recycle',
    title: '분리수거 / 쓰레기 버리기',
    description: '자취방 쓰레기 배출.',
    category: 'habit',
    difficulty: 'easy',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 3,
    createdAt: todayISO(),
  },

  // ── cooldownDays 4 (5일 주기) ─────────────────────────────────────
  {
    id: 'daily-laundry',
    title: '빨래 1회',
    description: '세탁 + 건조 사이클.',
    category: 'habit',
    difficulty: 'normal',
    statRewards: { PER: 1 },
    type: 'daily',
    recurring: true,
    cooldownDays: 4,
    createdAt: todayISO(),
  },
]

export const DEFAULT_MAIN_QUESTS: Quest[] = [
  {
    id: 'main-club',
    title: '경영·투자 학회 가입',
    description: '이번 학기/방학 동안 학회 가입 시험 통과. 자기소개서·면접·산업분석 준비 일체 포함.',
    category: 'career',
    difficulty: 'boss',
    statRewards: { INT: 6, PER: 4 },
    type: 'main',
    createdAt: todayISO(),
    completed: false,
  },
  {
    id: 'main-kbi-cert',
    title: 'KBI 금융 AI 리터러시 자격증 취득',
    description: '시험 응시 및 합격.',
    category: 'study',
    difficulty: 'apex',
    statRewards: { INT: 4, PER: 3 },
    type: 'main',
    createdAt: todayISO(),
    completed: false,
  },
  {
    id: 'main-cut',
    title: '체지방 감량: 70kg / 14% 도달',
    description: '현재 77kg → 70kg, 체지방률 14% 목표. 커팅 + 유산소 병행.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { VIT: 4, PER: 4 },
    type: 'main',
    createdAt: todayISO(),
    completed: false,
  },
  {
    id: 'main-gpa',
    title: '3학년 2학기 학점 4.0 이상',
    description: '현재 누적 3.96 → 학기 평점 4.0+ 사수.',
    category: 'study',
    difficulty: 'apex',
    statRewards: { INT: 4, PER: 3 },
    type: 'main',
    createdAt: todayISO(),
    completed: false,
  },
  {
    id: 'main-spend-monthly',
    title: '이번 달 소비 70만원 이하',
    description: '월 수입 125만원 기준 변동지출 70만원 이하 유지. 매월 1일 자동 재생성.',
    category: 'finance',
    difficulty: 'elite',
    statRewards: { PER: 4, SEN: 2 },
    type: 'main',
    createdAt: todayISO(),
    completed: false,
    resetCycle: 'monthly',
  },
]

export const DEFAULT_DUNGEONS: Quest[] = [
  {
    id: 'dungeon-reports',
    title: '산업/기업 분석 리포트 10편',
    description: '학회 면접 대비. 1편 = 1산업 또는 1기업 심층 분석 (PER/PBR, 사업구조, 경쟁사, 투자포인트). 1리포트 = 1단계.',
    category: 'career',
    difficulty: 'apex',
    statRewards: { INT: 6, PER: 3 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 10,
    currentSteps: 0,
  },
  {
    id: 'dungeon-cma-journal',
    title: 'CMA 실전 포트폴리오 운용 일지 12회',
    description: '실제 보유 CMA 자금 운용 기록. 월 1회 손익/리밸런싱/판단 근거 기록.',
    category: 'finance',
    difficulty: 'elite',
    statRewards: { INT: 4, SEN: 3 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 12,
    currentSteps: 0,
  },
  {
    id: 'dungeon-finance-books',
    title: '금융 도서 정복 8권',
    description: '학회 추천도서 + 클래식(현명한 투자자, 워런 버핏 주주서한, 증권분석 등). 1권 = 1단계.',
    category: 'study',
    difficulty: 'apex',
    statRewards: { INT: 6, PER: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 8,
    currentSteps: 0,
  },
  // ── 헬스 부위별 월간 던전 (매월 1일 자동 재생성) ────────────────
  {
    id: 'dungeon-arm-monthly',
    title: '이번 달 팔 운동 5회',
    description: '헬스장 팔 분할 루틴 5회 완료. 매월 1일 자동 재생성.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { STR: 4, AGI: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 5,
    currentSteps: 0,
    resetCycle: 'monthly',
  },
  {
    id: 'dungeon-back-monthly',
    title: '이번 달 등 운동 5회',
    description: '헬스장 등 분할 루틴 5회 완료. 매월 1일 자동 재생성.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { STR: 4, VIT: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 5,
    currentSteps: 0,
    resetCycle: 'monthly',
  },
  {
    id: 'dungeon-chest-monthly',
    title: '이번 달 가슴 운동 5회',
    description: '헬스장 가슴 분할 루틴 5회 완료. 매월 1일 자동 재생성.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { STR: 4, VIT: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 5,
    currentSteps: 0,
    resetCycle: 'monthly',
  },
  {
    id: 'dungeon-shoulder-monthly',
    title: '이번 달 어깨 운동 5회',
    description: '헬스장 어깨 분할 루틴 5회 완료. 매월 1일 자동 재생성.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { STR: 4, AGI: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 5,
    currentSteps: 0,
    resetCycle: 'monthly',
  },
  {
    id: 'dungeon-leg-monthly',
    title: '이번 달 하체 운동 3회',
    description: '헬스장 하체 분할 루틴 3회 완료. 매월 1일 자동 재생성.',
    category: 'workout',
    difficulty: 'elite',
    statRewards: { STR: 5, VIT: 2 },
    type: 'dungeon',
    createdAt: todayISO(),
    totalSteps: 3,
    currentSteps: 0,
    resetCycle: 'monthly',
  },
]

export const ITEM_POOL: Omit<Item, 'id' | 'acquiredAt'>[] = [
  // ── Consumables (14) ───────────────────────────────────────────────
  {
    name: '회복 포션',
    icon: '🧪',
    rarity: 'common',
    description: '피로를 덜어내는 기본 회복 물약. 추후 게이트 패널티 감소에 사용할 수 있다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'gate_penalty_reduction', value: 0.1, duration: 'next_gate' },
    ],
  },
  {
    name: '집중력 비약',
    icon: '🧠',
    rarity: 'common',
    description: '짧은 시간 동안 집중력을 끌어올리는 비약.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'study', value: 0.1, duration: 'next_quest' },
      { type: 'next_category_xp_bonus', category: 'career', value: 0.1, duration: 'next_quest' },
    ],
  },
  {
    name: '단백질 바',
    icon: '🍫',
    rarity: 'common',
    description: '훈련 전후에 먹기 좋은 보급품.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'workout', value: 0.1, duration: 'next_quest' },
      { type: 'next_category_xp_bonus', category: 'health', value: 0.1, duration: 'next_quest' },
    ],
  },
  {
    name: '맑은 물병',
    icon: '💧',
    rarity: 'common',
    description: '기본적인 수분 보급품. 다음 건강 퀘스트에 작은 도움을 준다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'health', value: 0.08, duration: 'next_quest' },
    ],
  },
  {
    name: '작은 행운 가루',
    icon: '✨',
    rarity: 'common',
    description: '희미한 행운이 담긴 가루. 다음 아이템 획득에 작은 영향을 준다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'temporary_drop_bonus', value: 0.05, duration: 'next_quest' },
    ],
  },
  {
    name: '짧은 집중 향',
    icon: '🕯️',
    rarity: 'common',
    description: '잠깐의 몰입을 돕는 향.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_quest_xp_bonus', value: 0.08, duration: 'next_quest' },
    ],
  },
  {
    name: '각성의 물약',
    icon: '🧪',
    rarity: 'uncommon',
    description: '잠깐 동안 전리품 감각을 날카롭게 만드는 물약.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'temporary_drop_bonus', value: 0.08, duration: 'next_quest' },
    ],
  },
  {
    name: '현자의 잉크',
    icon: '🖋️',
    rarity: 'uncommon',
    description: '기록의 질을 높이는 마법 잉크.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'study', value: 0.15, duration: 'next_quest' },
    ],
  },
  {
    name: '투사의 보급식',
    icon: '🥩',
    rarity: 'uncommon',
    description: '훈련 전 먹으면 몸이 가볍게 달아오른다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'workout', value: 0.15, duration: 'next_quest' },
    ],
  },
  {
    name: '행운의 룬 파편',
    icon: '🔹',
    rarity: 'rare',
    description: '다음 전리품의 격을 조금 끌어올리는 룬 조각.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'temporary_rarity_bonus', value: 0.02, duration: 'next_quest' },
    ],
  },
  {
    name: '시장 예지의 차',
    icon: '🍵',
    rarity: 'rare',
    description: '시장 흐름을 읽는 감각을 잠시 선명하게 만든다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'finance', value: 0.18, duration: 'next_quest' },
      { type: 'next_category_xp_bonus', category: 'career', value: 0.08, duration: 'next_quest' },
    ],
  },
  {
    name: '수도자의 안정향',
    icon: '🪷',
    rarity: 'rare',
    description: '흔들리는 마음을 가라앉히는 향.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_category_xp_bonus', category: 'mind', value: 0.15, duration: 'next_quest' },
      { type: 'next_category_xp_bonus', category: 'habit', value: 0.08, duration: 'next_quest' },
    ],
  },
  {
    name: '시스템 증폭제',
    icon: '🔮',
    rarity: 'epic',
    description: '다음 퀘스트의 보상 흐름을 강하게 증폭한다.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_quest_xp_bonus', value: 0.25, duration: 'next_quest' },
      { type: 'temporary_drop_bonus', value: 0.1, duration: 'next_quest' },
    ],
  },
  {
    name: '응급 붕대',
    icon: '🩹',
    rarity: 'epic',
    description: '위험한 게이트에서 피해를 줄이기 위한 응급 도구.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'gate_penalty_reduction', value: 0.25, duration: 'next_gate' },
    ],
  },
  {
    name: '운명의 엘릭서',
    icon: '🌌',
    rarity: 'legendary',
    description: '단 한 번, 운명의 흐름을 크게 비트는 전설의 영약.',
    equippable: false,
    consumable: true,
    consumableEffects: [
      { type: 'next_quest_xp_bonus', value: 0.35, duration: 'next_quest' },
      { type: 'temporary_rarity_bonus', value: 0.03, duration: 'next_quest' },
    ],
  },

  // ── Equipment: Common (5) ──────────────────────────────────────────
  // ── Equipment: Common (5) ──────────────────────────────────────────
  {
    name: '낡은 단검',
    icon: '🗡️',
    rarity: 'common',
    description: '미루기를 살짝 베어낼 수 있는 초보자의 무기.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [{ type: 'xp_bonus', category: 'habit', value: 0.01 }],
  },
  {
    name: '수련용 목검',
    icon: '⚔️',
    rarity: 'common',
    description: '기본기를 반복하기 위한 낡은 목검.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [{ type: 'xp_bonus', category: 'workout', value: 0.01 }],
  },
  {
    name: '초심자의 노트',
    icon: '📓',
    rarity: 'common',
    description: '처음 배운 지식을 붙잡아두는 작은 노트.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [{ type: 'xp_bonus', category: 'study', value: 0.01 }],
  },
  {
    name: '낡은 손목보호대',
    icon: '🧤',
    rarity: 'common',
    description: '무리하지 않고 하루를 버티게 해주는 보호대.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [{ type: 'xp_bonus', category: 'health', value: 0.01 }],
  },
  {
    name: '작은 행운석',
    icon: '🪨',
    rarity: 'common',
    description: '아주 희미하게 전리품의 기운을 끌어당긴다.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'drop_bonus', value: 0.01 }],
  },

  // ── Equipment: Uncommon (9) ────────────────────────────────────────
  // ── Equipment: Uncommon (9) ────────────────────────────────────────
  {
    name: '강철의 책',
    icon: '📘',
    rarity: 'uncommon',
    description: '읽을 때마다 지식의 무게가 쌓이는 책.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [{ type: 'xp_bonus', category: 'study', value: 0.03 }],
  },
  {
    name: '의지의 룬',
    icon: '🔷',
    rarity: 'uncommon',
    description: '한 번 더 버틸 수 있게 해주는 작은 룬.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'stat_bonus', stat: 'PER', value: 2 }],
  },
  {
    name: '시장 관측자의 펜',
    icon: '🖋️',
    rarity: 'uncommon',
    description: '시장의 흔적을 기록하기 위한 펜.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [{ type: 'xp_bonus', category: 'finance', value: 0.03 }],
  },
  {
    name: '집중의 반지',
    icon: '💍',
    rarity: 'uncommon',
    description: '흐트러진 정신을 한곳에 묶어두는 반지.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'stat_bonus', stat: 'INT', value: 2 }],
  },
  {
    name: '루틴의 팔찌',
    icon: '📿',
    rarity: 'uncommon',
    description: '반복을 의식으로 바꾸는 팔찌.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'xp_bonus', category: 'habit', value: 0.03 }],
  },
  {
    name: '중량 벨트',
    icon: '🏋️',
    rarity: 'uncommon',
    description: '몸의 중심을 단단히 잡아주는 훈련 장비.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [{ type: 'xp_bonus', category: 'workout', value: 0.03 }],
  },
  {
    name: '정돈된 코트',
    icon: '🧥',
    rarity: 'uncommon',
    description: '외형을 정돈하면 마음가짐도 정돈된다.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.02 },
      { type: 'xp_bonus', category: 'habit', value: 0.01 },
    ],
  },
  {
    name: '침묵의 부적',
    icon: '🧿',
    rarity: 'uncommon',
    description: '불필요한 소음을 잠재우는 작은 부적.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'xp_bonus', category: 'mind', value: 0.03 }],
  },
  {
    name: '견습 헌터 배지',
    icon: '🎖️',
    rarity: 'uncommon',
    description: '이제 막 자신의 길을 찾기 시작한 헌터의 배지.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.01 },
      { type: 'xp_bonus', category: 'study', value: 0.01 },
      { type: 'xp_bonus', category: 'workout', value: 0.01 },
    ],
  },

  // ── Equipment: Rare (10) ───────────────────────────────────────────
  {
    name: '바람의 신발',
    icon: '👟',
    rarity: 'rare',
    description: '달릴 때 발이 가벼워진다.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [{ type: 'xp_bonus', category: 'workout', value: 0.04 }],
  },
  {
    name: '각성자의 목걸이',
    icon: '📿',
    rarity: 'rare',
    description: '잠재된 무언가가 깨어나는 목걸이.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'rarity_bonus', value: 0.01 }],
  },
  {
    name: '금안의 렌즈',
    icon: '🔎',
    rarity: 'rare',
    description: '숫자 너머의 흐름을 보기 위한 렌즈.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [{ type: 'xp_bonus', category: 'finance', value: 0.05 }],
  },
  {
    name: '서고의 열쇠',
    icon: '🗝️',
    rarity: 'rare',
    description: '닫힌 지식의 문을 여는 열쇠.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'study', value: 0.04 },
      { type: 'xp_bonus', category: 'career', value: 0.02 },
    ],
  },
  {
    name: '분석가의 만년필',
    icon: '🖊️',
    rarity: 'rare',
    description: '흩어진 사실을 하나의 논리로 꿰는 펜.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.04 },
      { type: 'xp_bonus', category: 'finance', value: 0.02 },
    ],
  },
  {
    name: '강철 손목보호대',
    icon: '🧤',
    rarity: 'rare',
    description: '무게를 견디는 손목에 힘을 더한다.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [
      { type: 'stat_bonus', stat: 'STR', value: 2 },
      { type: 'xp_bonus', category: 'workout', value: 0.03 },
    ],
  },
  {
    name: '고요의 반지',
    icon: '💍',
    rarity: 'rare',
    description: '흔들리는 마음을 고요하게 붙잡는 반지.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [
      { type: 'xp_bonus', category: 'mind', value: 0.04 },
      { type: 'stat_bonus', stat: 'PER', value: 1 },
    ],
  },
  {
    name: '시간의 모래시계',
    icon: '⌛',
    rarity: 'rare',
    description: '흘러가는 시간을 의식하게 만드는 작은 모래시계.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'habit', value: 0.04 },
      { type: 'xp_bonus', category: 'mind', value: 0.02 },
    ],
  },
  {
    name: '그림자 망토',
    icon: '🧥',
    rarity: 'rare',
    description: '조용히 움직이는 자에게 전리품이 따른다.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [{ type: 'drop_bonus', value: 0.03 }],
  },
  {
    name: '사냥꾼의 단검',
    icon: '🗡️',
    rarity: 'rare',
    description: '작은 목표를 빠르게 처리하는 사냥꾼의 무기.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.03 },
      { type: 'xp_bonus', category: 'habit', value: 0.03 },
    ],
  },

  // ── Epic (8) ───────────────────────────────────────────────────────
  {
    name: '검은 정장',
    icon: '🕴️',
    rarity: 'epic',
    description: '자세가 바뀌면 인생이 바뀐다.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [{ type: 'xp_bonus', category: 'career', value: 0.06 }],
    combatSkillIds: ['equip-black-suit-guard'],
  },
  {
    name: '그림자 단검',
    icon: '🗡️',
    rarity: 'epic',
    description: '미루기를 베어버린다.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [
      { type: 'xp_bonus', category: 'habit', value: 0.06 },
      { type: 'xp_bonus', category: 'mind', value: 0.02 },
    ],
    combatSkillIds: ['equip-shadow-slash'],
  },
  {
    name: '황금 나침반',
    icon: '🧭',
    rarity: 'epic',
    description: '자본의 흐름이 향하는 방향을 가리킨다.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [{ type: 'xp_bonus', category: 'finance', value: 0.07 }],
  },
  {
    name: '금서의 책갈피',
    icon: '🔖',
    rarity: 'epic',
    description: '한 번 읽은 지식을 깊은 곳에 고정한다.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'study', value: 0.06 },
      { type: 'stat_bonus', stat: 'INT', value: 2 },
    ],
  },
  {
    name: '계율의 로브',
    icon: '🥋',
    rarity: 'epic',
    description: '흐트러짐을 허락하지 않는 수도자의 로브.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [
      { type: 'xp_bonus', category: 'habit', value: 0.06 },
      { type: 'stat_bonus', stat: 'PER', value: 2 },
    ],
  },
  {
    name: '투사의 장갑',
    icon: '🥊',
    rarity: 'epic',
    description: '한계를 밀어붙이는 자의 손에 맞는 장갑.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [
      { type: 'xp_bonus', category: 'workout', value: 0.06 },
      { type: 'stat_bonus', stat: 'STR', value: 2 },
    ],
  },
  {
    name: '새벽의 귀걸이',
    icon: '💎',
    rarity: 'epic',
    description: '새벽의 고요함을 머금은 귀걸이.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [
      { type: 'xp_bonus', category: 'health', value: 0.05 },
      { type: 'xp_bonus', category: 'mind', value: 0.03 },
    ],
  },
  {
    name: '균형의 문장',
    icon: '⚜️',
    rarity: 'epic',
    description: '한쪽으로 치우치지 않는 성장의 상징.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.03 },
      { type: 'xp_bonus', category: 'study', value: 0.03 },
      { type: 'xp_bonus', category: 'workout', value: 0.03 },
      { type: 'xp_bonus', category: 'habit', value: 0.03 },
    ],
  },

  // ── Legendary (6) ──────────────────────────────────────────────────
  {
    name: '왕의 검',
    icon: '👑',
    rarity: 'legendary',
    description: '오직 의지로 단련된 자에게 허락된 무기.',
    equippable: true,
    consumable: false,
    slot: 'weapon',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.08 },
      { type: 'xp_bonus', category: 'workout', value: 0.05 },
    ],
    combatSkillIds: ['equip-kings-command'],
  },
  {
    name: '시스템의 조각',
    icon: '🔮',
    rarity: 'legendary',
    description: '이걸 손에 넣었다면 진짜 헌터다.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'rarity_bonus', value: 0.02 },
      { type: 'drop_bonus', value: 0.03 },
    ],
    combatSkillIds: ['equip-system-pulse'],
  },
  {
    name: '황금안의 수정구',
    icon: '🟡',
    rarity: 'legendary',
    description: '시장 너머의 흐름을 비추는 황금빛 수정구.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [{ type: 'xp_bonus', category: 'finance', value: 0.1 }],
  },
  {
    name: '심연의 기록서',
    icon: '📚',
    rarity: 'legendary',
    description: '진실에 가까운 기록일수록 더 깊은 곳에 잠겨 있다.',
    equippable: true,
    consumable: false,
    slot: 'artifact',
    effects: [
      { type: 'xp_bonus', category: 'study', value: 0.08 },
      { type: 'xp_bonus', category: 'career', value: 0.05 },
    ],
  },
  {
    name: '시간의 회중시계',
    icon: '⏱️',
    rarity: 'legendary',
    description: '흐트러진 시간을 다시 붙잡는 고대 장신구.',
    equippable: true,
    consumable: false,
    slot: 'accessory',
    effects: [
      { type: 'xp_bonus', category: 'habit', value: 0.08 },
      { type: 'xp_bonus', category: 'mind', value: 0.05 },
      { type: 'stat_bonus', stat: 'PER', value: 3 },
    ],
  },
  {
    name: '그림자 왕관',
    icon: '👑',
    rarity: 'legendary',
    description: '그림자 위에 선 자만이 쓸 수 있는 왕관.',
    equippable: true,
    consumable: false,
    slot: 'armor',
    effects: [
      { type: 'xp_bonus', category: 'career', value: 0.04 },
      { type: 'xp_bonus', category: 'study', value: 0.04 },
      { type: 'xp_bonus', category: 'workout', value: 0.04 },
      { type: 'xp_bonus', category: 'habit', value: 0.04 },
      { type: 'drop_bonus', value: 0.02 },
    ],
  },
]

// ── Gate / Combat Seed Data ────────────────────────────────────────

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  {
    id: 'basic-attack',
    name: '기본 공격',
    description: '가장 기본적인 공격.',
    ownerType: 'common',
    type: 'attack',
    power: 1.0,
    cooldownTurns: 0,
  },
  {
    id: 'skill-golden-eye-insight',
    name: '약점 간파',
    description: '적의 빈틈을 읽어 치명타 감각을 끌어올린다.',
    ownerType: 'job',
    type: 'buff',
    cooldownTurns: 4,
    effect: {
      stat: 'critRate',
      value: 0.08,
      durationTurns: 3,
      target: 'self',
    },
  },
  {
    id: 'skill-iron-charge',
    name: '강철 돌진',
    description: '단련된 육체로 정면 돌파한다.',
    ownerType: 'job',
    type: 'attack',
    power: 1.35,
    cooldownTurns: 3,
  },
  {
    id: 'skill-grimoire-focus',
    name: '금서 집중',
    description: '흩어진 정보를 압축해 공격의 정확도를 끌어올린다.',
    ownerType: 'job',
    type: 'buff',
    cooldownTurns: 4,
    effect: {
      stat: 'accuracy',
      value: 0.04,
      durationTurns: 3,
      target: 'self',
    },
  },
  {
    id: 'skill-archive-analysis',
    name: '방어식 해체',
    description: '적의 구조를 분석해 방어 태세를 무너뜨린다.',
    ownerType: 'job',
    type: 'debuff',
    cooldownTurns: 4,
    effect: {
      stat: 'def',
      value: -8,
      durationTurns: 3,
      target: 'enemy',
    },
  },
  {
    id: 'skill-silent-guard',
    name: '침묵의 반격식',
    description: '호흡을 가라앉혀 피해를 줄이고, 빈틈을 노려 반격한다.',
    ownerType: 'job',
    type: 'buff',
    cooldownTurns: 4,
    effects: [
      {
        kind: 'damage_reduction',
        value: 0.15,
        durationTurns: 3,
        target: 'self',
      },
      {
        kind: 'counter',
        value: 0,
        counterRate: 0.45,
        counterPower: 0.55,
        durationTurns: 3,
        target: 'self',
      },
    ],
  },
  {
    id: 'skill-fate-balance',
    name: '운명 조율',
    description: '흐트러진 균형을 바로잡아 속도를 끌어올린다.',
    ownerType: 'job',
    type: 'buff',
    cooldownTurns: 5,
    effect: {
      stat: 'speed',
      value: 8,
      durationTurns: 2,
      target: 'self',
    },
  },
  {
    id: 'skill-fate-alignment',
    name: '운명의 조율',
    description: '흩어진 흐름을 정렬해 전투 감각을 고르게 끌어올린다.',
    ownerType: 'job',
    type: 'buff',
    cooldownTurns: 5,
    effect: {
      stat: 'atk',
      value: 5,
      durationTurns: 3,
      target: 'self',
    },
  },
  {
    id: 'equip-shadow-slash',
    name: '그림자 베기',
    description: '그림자처럼 파고들어 적을 빠르게 벤다.',
    ownerType: 'equipment',
    type: 'attack',
    power: 1.25,
    cooldownTurns: 3,
  },
  {
    id: 'equip-kings-command',
    name: '왕의 명령',
    description: '전장을 지배하는 의지로 공격 태세를 끌어올린다.',
    ownerType: 'equipment',
    type: 'buff',
    cooldownTurns: 5,
    effects: [
      {
        kind: 'stat',
        stat: 'atk',
        value: 6,
        durationTurns: 3,
        target: 'self',
      },
      {
        kind: 'stat',
        stat: 'critRate',
        value: 0.04,
        durationTurns: 3,
        target: 'self',
      },
    ],
  },
  {
    id: 'equip-system-pulse',
    name: '시스템 펄스',
    description: '시스템의 파동을 방출해 적의 방어 구조를 흔든다.',
    ownerType: 'equipment',
    type: 'debuff',
    cooldownTurns: 5,
    effect: {
      kind: 'stat',
      stat: 'def',
      value: -6,
      durationTurns: 3,
      target: 'enemy',
    },
  },
  {
    id: 'equip-black-suit-guard',
    name: '흐트러짐 없는 자세',
    description: '흔들리지 않는 자세로 피해를 흘려낸다.',
    ownerType: 'equipment',
    type: 'buff',
    cooldownTurns: 5,
    effect: {
      kind: 'damage_reduction',
      value: 0.1,
      durationTurns: 3,
      target: 'self',
    },
  },
  {
    id: 'monster-bite',
    name: '날카로운 이빨',
    description: '작은 몬스터의 기본 공격 스킬.',
    ownerType: 'monster',
    type: 'attack',
    power: 1.1,
    cooldownTurns: 2,
  },
  {
    id: 'monster-lazy-curse',
    name: '나태의 저주',
    description: '대상의 움직임을 둔하게 만든다.',
    ownerType: 'monster',
    type: 'debuff',
    cooldownTurns: 4,
    effect: {
      stat: 'speed',
      value: -5,
      durationTurns: 2,
      target: 'enemy',
    },
  },
  {
    id: 'monster-rift-scratch',
    name: '균열 할퀴기',
    description: '균열의 기운을 담아 거칠게 할퀸다.',
    ownerType: 'monster',
    type: 'attack',
    power: 1.2,
    cooldownTurns: 3,
  },
  {
    id: 'monster-memory-fog',
    name: '망각의 안개',
    description: '집중을 흐리게 만들어 명중 감각을 떨어뜨린다.',
    ownerType: 'monster',
    type: 'debuff',
    cooldownTurns: 4,
    effect: {
      stat: 'accuracy',
      value: -0.05,
      durationTurns: 2,
      target: 'enemy',
    },
  },
]

export const MONSTER_DEFINITIONS: MonsterDefinition[] = [
  {
    id: 'rift-rat',
    name: '균열 쥐',
    description: '작은 균열에서 흘러나온 하급 몬스터.',
    rank: 'E',
    stats: {
      maxHp: 133,
      atk: 25,
      def: 10,
      speed: 12,
      critRate: 0.03,
      accuracy: 0.9,
      evasionRate: 0.02,
    },
    skillIds: ['monster-bite'],
  },
  {
    id: 'rift-stray',
    name: '균열 들개',
    description: '균열의 냄새를 쫓아 현실로 흘러나온 민첩한 몬스터.',
    rank: 'E',
    stats: {
      maxHp: 100,
      atk: 24,
      def: 10,
      speed: 18,
      critRate: 0.04,
      accuracy: 0.9,
      evasionRate: 0.04,
    },
    skillIds: ['monster-bite', 'monster-rift-scratch'],
  },
  {
    id: 'lazy-goblin',
    name: '나태의 고블린',
    description: '의지를 갉아먹는 D급 몬스터.',
    rank: 'D',
    stats: {
      maxHp: 350,
      atk: 80,
      def: 31,
      speed: 14,
      critRate: 0.05,
      accuracy: 0.9,
      evasionRate: 0.04,
    },
    skillIds: ['monster-bite', 'monster-lazy-curse'],
  },
  {
    id: 'sloth-brute',
    name: '나태의 완력병',
    description: '무거운 몸으로 천천히 밀고 들어오는 D급 몬스터.',
    rank: 'D',
    stats: {
      maxHp: 210,
      atk: 42,
      def: 28,
      speed: 10,
      critRate: 0.04,
      accuracy: 0.88,
      evasionRate: 0.02,
    },
    skillIds: ['monster-rift-scratch', 'monster-lazy-curse'],
  },
  {
    id: 'forgetting-warden',
    name: '망각의 파수꾼',
    description: '기록과 집중을 흐리게 만드는 C급 파수꾼.',
    rank: 'C',
    // 12-1E: HP/ATK/DEF 상향 — main/dungeon 누적 빌드의 C급 정복 승률(97%)을 50~70%대로 조정.
    //         HP 575→780 (+36%), ATK 88→105 (+19%), DEF 46→58 (+26%).
    stats: {
      maxHp: 780,
      atk: 105,
      def: 58,
      speed: 20,
      critRate: 0.08,
      accuracy: 0.92,
      evasionRate: 0.06,
    },
    skillIds: ['monster-lazy-curse', 'monster-memory-fog'],
  },
  // ── 12-2A: C급 콘텐츠 다양화 ──────────────────────────────────────
  {
    id: 'fatigue-warden',
    name: '피로의 간수',
    description: '느리지만 끈질긴 방어형 C급 몬스터. 화력으론 좀처럼 뚫리지 않는다.',
    rank: 'C',
    // 12-2A 2차: HP 920→850, DEF 82→72 (Build E 1차 16% → 약 40~50% 목표). draw 3~4%도 같이 완화.
    stats: {
      maxHp: 850,
      atk: 88,
      def: 72,
      speed: 14,
      critRate: 0.05,
      accuracy: 0.92,
      evasionRate: 0.04,
    },
    skillIds: ['monster-rift-scratch', 'monster-lazy-curse'],
  },
  {
    id: 'memory-tracker',
    name: '기억 추적자',
    description: '망각의 서고 외곽을 떠도는 C급 정찰병. 단독으로는 약하지만 짝을 이뤄 다닌다.',
    rank: 'C',
    // 12-2A 2차: HP 460→540 (+17%), ATK 80→88 (+10%). wave 1차에서 Build E 90% → 50~65% 목표.
    stats: {
      maxHp: 540,
      atk: 88,
      def: 40,
      speed: 17,
      critRate: 0.06,
      accuracy: 0.9,
      evasionRate: 0.05,
    },
    skillIds: ['monster-bite', 'monster-memory-fog'],
  },
  {
    id: 'memory-scout',
    name: '기억 정찰자',
    description: '추적자보다 빠르고 가볍지만, 한 번에 큰 피해를 노리는 후위 C급 몬스터.',
    rank: 'C',
    // 12-2A 2차: HP 380→450 (+18%), ATK 95→105 (+11%). 2차 wave에서도 누적 피해 강화.
    stats: {
      maxHp: 450,
      atk: 105,
      def: 35,
      speed: 22,
      critRate: 0.08,
      accuracy: 0.91,
      evasionRate: 0.06,
    },
    skillIds: ['monster-bite', 'monster-rift-scratch'],
  },
  {
    id: 'greed-warden',
    name: '탐욕의 파수꾼',
    description: '한 번의 일격에 모든 것을 거는 공격형 C급 몬스터. HP는 낮지만 위협적이다.',
    rank: 'C',
    // 12-2A 2차: ATK 130→120 (-8%), HP 700→680. Build E 1차 28% → 35~50% 목표.
    stats: {
      maxHp: 680,
      atk: 120,
      def: 45,
      speed: 22,
      critRate: 0.10,
      accuracy: 0.92,
      evasionRate: 0.07,
    },
    skillIds: ['monster-rift-scratch', 'monster-bite'],
  },
]

export const GATE_DEFINITIONS: GateDefinition[] = [
  {
    id: 'gate-rift-alley',
    name: '균열의 골목',
    description: '작은 균열이 열린 골목. 하급 몬스터의 기척이 느껴진다.',
    rank: 'E',
    recommendedLevel: 5,
    recommendedPower: 300,
    monsterIds: ['rift-rat'],
    rewardTableId: 'reward-gate-e-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-rift-backstreet',
    name: '뒤틀린 뒷골목',
    description: '작지만 빠른 몬스터가 배회하는 E급 균열.',
    rank: 'E',
    recommendedLevel: 7,
    recommendedPower: 300,
    monsterIds: ['rift-stray'],
    rewardTableId: 'reward-gate-e-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-rift-nest',
    name: '균열의 둥지',
    description: '작은 균열 생물들이 연속해서 튀어나오는 E급 게이트.',
    rank: 'E',
    recommendedLevel: 7,
    recommendedPower: 420,
    monsterIds: ['rift-rat', 'rift-stray'],
    rewardTableId: 'reward-gate-e-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-lair-of-sloth',
    name: '나태의 소굴',
    description: '의지를 갉아먹는 기운이 고여 있는 D급 게이트.',
    rank: 'D',
    recommendedLevel: 10,
    recommendedPower: 650,
    monsterIds: ['lazy-goblin'],
    rewardTableId: 'reward-gate-d-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-sloth-patrol',
    name: '나태의 순찰로',
    description: '균열 생물과 나태의 고블린이 이어서 나타나는 D급 게이트.',
    rank: 'D',
    recommendedLevel: 12,
    recommendedPower: 780,
    monsterIds: ['rift-rat', 'lazy-goblin'],
    rewardTableId: 'reward-gate-d-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-archive-of-forgetting',
    name: '망각의 서고',
    description: '집중과 기록을 삼키는 C급 게이트.',
    rank: 'C',
    recommendedLevel: 15,
    // 12-1E: 870 → 1000. main/dungeon 누적 빌드 파워(~867)와의 ratio를 0.87로 만들어 high risk 유지.
    recommendedPower: 1000,
    monsterIds: ['forgetting-warden'],
    rewardTableId: 'reward-gate-c-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  // ── 12-2A: C급 게이트 3개 추가 ────────────────────────────────────
  {
    id: 'gate-corridor-of-fatigue',
    name: '피로의 회랑',
    description: '시간이 무겁게 흐르는 C급 게이트. 단단한 방벽 앞에서 화력이 시험받는다.',
    rank: 'C',
    recommendedLevel: 16,
    // 방어형 — 화력 부족하면 오래 끌리지만 DEF/HP가 높아 공격 못 뚫으면 결국 패배.
    recommendedPower: 980,
    monsterIds: ['fatigue-warden'],
    rewardTableId: 'reward-gate-c-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-rift-training-grounds',
    name: '균열의 훈련장',
    description: '기억 추적자와 정찰자가 짝을 이뤄 다니는 C급 wave 게이트.',
    rank: 'C',
    recommendedLevel: 17,
    // wave형 — 단일 보스보다 약한 몹 둘이 누적 피해를 준다.
    recommendedPower: 1050,
    monsterIds: ['memory-tracker', 'memory-scout'],
    rewardTableId: 'reward-gate-c-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
  {
    id: 'gate-greed-vault',
    name: '탐욕의 금고',
    description: '단 한 번의 일격이 모든 것을 결정짓는 C급 공격형 게이트. 짧지만 위험하다.',
    rank: 'C',
    recommendedLevel: 17,
    // 공격형 — 화력은 높지만 HP가 낮음. 빠르게 끝나지만 한 방에 무너질 수 있음.
    recommendedPower: 1050,
    monsterIds: ['greed-warden'],
    rewardTableId: 'reward-gate-c-basic',
    failPenaltyId: 'penalty-gate-basic',
    expiresInHours: 24,
  },
]

export const GATE_REWARD_TABLES: GateRewardTable[] = [
  {
    id: 'reward-gate-e-basic',
    name: 'E급 게이트 기본 보상',
    xp: 80,
    itemDropChance: 0.35,
    rarityBias: {
      common: 0.6,
      uncommon: 0.3,
      rare: 0.1,
    },
  },
  {
    id: 'reward-gate-d-basic',
    name: 'D급 게이트 기본 보상',
    xp: 140,
    itemDropChance: 0.45,
    rarityBias: {
      common: 0.3,
      uncommon: 0.4,
      rare: 0.25,
      epic: 0.05,
    },
  },
  {
    id: 'reward-gate-c-basic',
    name: 'C급 게이트 기본 보상',
    xp: 220,
    itemDropChance: 0.55,
    rarityBias: {
      uncommon: 0.25,
      rare: 0.5,
      epic: 0.2,
      legendary: 0.05,
    },
  },
]

export const GATE_PENALTIES: GatePenalty[] = [
  {
    id: 'penalty-gate-basic',
    name: '기본 게이트 패널티',
    staminaCost: 50,
    injuryHours: 6,
  },
]

// ── Random Quest Pool ──────────────────────────────────────────────

export const RANDOM_QUEST_POOL: RandomQuestTemplate[] = [
  // ── Career / Finance (high weight) ────────────────────────────────
  {
    id: 'rq-market-sector-check',
    title: '시장 기류 탐지',
    description: '오늘 오른 업종 1개와 내린 업종 1개를 확인하라.',
    category: 'finance',
    difficulty: 'normal',
    xp: 40,
    weight: 8,
  },
  {
    id: 'rq-report-title-scan',
    title: '리포트 정찰',
    description: '증권사 리서치 리포트 제목 5개를 훑어보라.',
    category: 'career',
    difficulty: 'easy',
    xp: 25,
    weight: 8,
  },
  {
    id: 'rq-stock-ten-min',
    title: '종목 감응',
    description: '관심 종목 하나를 10분만 살펴보라.',
    category: 'finance',
    difficulty: 'normal',
    xp: 45,
    weight: 7,
  },
  {
    id: 'rq-disclosure-read',
    title: '공시 해독',
    description: '최근 공시 하나의 제목을 보고 의미를 추정해보라.',
    category: 'finance',
    difficulty: 'normal',
    xp: 45,
    weight: 6,
  },
  {
    id: 'rq-club-sentence',
    title: '지원자의 문장',
    description: '학회 지원용 자기소개 문장 3줄을 다듬어라.',
    category: 'career',
    difficulty: 'hard',
    xp: 70,
    weight: 5,
  },
  {
    id: 'rq-industry-toc',
    title: '산업의 입구',
    description: '산업 리포트 하나를 열고 목차만 읽어라.',
    category: 'career',
    difficulty: 'normal',
    xp: 45,
    weight: 6,
  },

  // ── Study (medium-high weight) ────────────────────────────────────
  {
    id: 'rq-class-summary',
    title: '지식 압축',
    description: '오늘 수업 내용 또는 공부한 내용을 5줄로 요약하라.',
    category: 'study',
    difficulty: 'normal',
    xp: 40,
    weight: 7,
  },
  {
    id: 'rq-concept-review',
    title: '개념 회수',
    description: '경제학/전공 개념 하나를 10분 복습하라.',
    category: 'study',
    difficulty: 'normal',
    xp: 40,
    weight: 7,
  },
  {
    id: 'rq-calendar-check',
    title: '일정 정찰',
    description: '과제/시험/학회 관련 일정을 한 번 점검하라.',
    category: 'study',
    difficulty: 'easy',
    xp: 25,
    weight: 5,
  },
  {
    id: 'rq-article-one-line',
    title: '한 줄 기록',
    description: '전공/금융 관련 기사 하나를 읽고 한 문장으로 요약하라.',
    category: 'study',
    difficulty: 'normal',
    xp: 45,
    weight: 5,
  },

  // ── Workout / Health (medium weight) ──────────────────────────────
  {
    id: 'rq-seongbuk-walk',
    title: '성북천 순찰',
    description: '성북천 또는 집 근처를 15분 산책하라.',
    category: 'health',
    difficulty: 'easy',
    xp: 25,
    weight: 6,
  },
  {
    id: 'rq-protein-check',
    title: '단백질 점검',
    description: '오늘 먹은 단백질을 대충 계산해보라.',
    category: 'health',
    difficulty: 'easy',
    xp: 20,
    weight: 5,
  },
  {
    id: 'rq-water-plus',
    title: '수분 보급',
    description: '물 500ml를 추가로 마셔라.',
    category: 'health',
    difficulty: 'easy',
    xp: 20,
    weight: 5,
  },
  {
    id: 'rq-cardio-extra',
    title: '심폐 예열',
    description: '유산소 10분을 추가하라.',
    category: 'workout',
    difficulty: 'normal',
    xp: 40,
    weight: 4,
  },
  {
    id: 'rq-stretch-seven',
    title: '관절 해방',
    description: '스트레칭 7분을 수행하라.',
    category: 'health',
    difficulty: 'easy',
    xp: 25,
    weight: 5,
  },

  // ── Habit (medium weight) ─────────────────────────────────────────
  {
    id: 'rq-desk-clean',
    title: '작전 구역 정리',
    description: '책상 위를 5분 정리하라.',
    category: 'habit',
    difficulty: 'easy',
    xp: 20,
    weight: 7,
  },
  {
    id: 'rq-sink-zero',
    title: '싱크대 정화',
    description: '싱크대를 비우거나 설거지 상태를 정리하라.',
    category: 'habit',
    difficulty: 'easy',
    xp: 25,
    weight: 5,
  },
  {
    id: 'rq-fridge-check',
    title: '보급품 점검',
    description: '냉장고 안에서 버릴 음식이 있는지 확인하라.',
    category: 'habit',
    difficulty: 'easy',
    xp: 20,
    weight: 4,
  },
  {
    id: 'rq-tomorrow-clothes',
    title: '장비 사전 배치',
    description: '내일 입을 옷이나 챙길 물건을 미리 준비하라.',
    category: 'habit',
    difficulty: 'easy',
    xp: 20,
    weight: 4,
  },

  // ── Mind (low weight) ─────────────────────────────────────────────
  {
    id: 'rq-phone-away',
    title: '소음 차단',
    description: '폰을 20분 동안 손이 닿지 않는 곳에 둬라.',
    category: 'mind',
    difficulty: 'normal',
    xp: 35,
    weight: 4,
  },
  {
    id: 'rq-one-worry',
    title: '불안 정찰',
    description: '지금 걱정 하나를 적고, 다음 행동 하나를 정하라.',
    category: 'mind',
    difficulty: 'easy',
    xp: 25,
    weight: 3,
  },
  {
    id: 'rq-ten-min-focus',
    title: '단일 명령 수행',
    description: '10분 타이머를 켜고 한 가지 일만 하라.',
    category: 'mind',
    difficulty: 'normal',
    xp: 35,
    weight: 4,
  },
  {
    id: 'rq-good-one',
    title: '전리품 기록',
    description: '오늘 잘한 것 1개를 기록하라.',
    category: 'mind',
    difficulty: 'easy',
    xp: 20,
    weight: 3,
  },
]
